// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: adU29zJd9uLGW9TewABBsV
// Component: y-2j-fa4twS1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import VotingCard from "../../VotingCard"; // plasmic-import: oAGE1uzhgryh/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_fusion_lab.module.css"; // plasmic-import: adU29zJd9uLGW9TewABBsV/projectcss
import sty from "./PlasmicVotingSection.module.css"; // plasmic-import: y-2j-fa4twS1/css

createPlasmicElementProxy;

export type PlasmicVotingSection__VariantMembers = {};
export type PlasmicVotingSection__VariantsArgs = {};
type VariantPropType = keyof PlasmicVotingSection__VariantsArgs;
export const PlasmicVotingSection__VariantProps = new Array<VariantPropType>();

export type PlasmicVotingSection__ArgsType = {};
type ArgPropType = keyof PlasmicVotingSection__ArgsType;
export const PlasmicVotingSection__ArgProps = new Array<ArgPropType>();

export type PlasmicVotingSection__OverridesType = {
  vote?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultVotingSectionProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVotingSection__RenderFunc(props: {
  variants: PlasmicVotingSection__VariantsArgs;
  args: PlasmicVotingSection__ArgsType;
  overrides: PlasmicVotingSection__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"vote"}
      data-plasmic-override={overrides.vote}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.vote
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <VotingCard
          className={classNames("__wab_instance", sty.votingCard__hnUh1)}
          proposalName={"Proposal A"}
        />

        <VotingCard
          className={classNames("__wab_instance", sty.votingCard__aV27L)}
          proposalName={"Proposal B"}
        />

        <VotingCard
          className={classNames("__wab_instance", sty.votingCard___4M1VA)}
          proposalName={
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {"Proposal C"}
            </div>
          }
        />

        <VotingCard
          className={classNames("__wab_instance", sty.votingCard__dZYnU)}
          proposalName={"Proposal D"}
        />

        <VotingCard
          className={classNames("__wab_instance", sty.votingCard__bhY)}
          proposalName={"Proposal E"}
        />
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  vote: ["vote", "freeBox", "text"],
  freeBox: ["freeBox", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  vote: "div";
  freeBox: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVotingSection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVotingSection__VariantsArgs;
    args?: PlasmicVotingSection__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVotingSection__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVotingSection__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVotingSection__ArgProps,
          internalVariantPropNames: PlasmicVotingSection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVotingSection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "vote") {
    func.displayName = "PlasmicVotingSection";
  } else {
    func.displayName = `PlasmicVotingSection.${nodeName}`;
  }
  return func;
}

export const PlasmicVotingSection = Object.assign(
  // Top-level PlasmicVotingSection renders the root element
  makeNodeComponent("vote"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicVotingSection
    internalVariantProps: PlasmicVotingSection__VariantProps,
    internalArgProps: PlasmicVotingSection__ArgProps
  }
);

export default PlasmicVotingSection;
/* prettier-ignore-end */
